# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokensaver < Formula
  desc "Local MCP server that turns web pages, PDFs, Office files and JSON into compact, LLM-ready text"
  homepage "https://github.com/use-tokesaver/tokensaver"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.1/tokensaver_0.2.1_darwin_amd64.tar.gz"
      sha256 "94c630ecb90932f2f71841fdfb78e5510c24b11305a2f81795a5612793beacc9"

      define_method(:install) do
        bin.install "tokensaver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.1/tokensaver_0.2.1_darwin_arm64.tar.gz"
      sha256 "dcbaffc48b3284c05409819cc8ed725092ab69f08d11f146583084678c48760b"

      define_method(:install) do
        bin.install "tokensaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.1/tokensaver_0.2.1_linux_amd64.tar.gz"
      sha256 "ab43c0574d850f64b288b297b00f21ed6a90868fea9e0f9496dc57024afab83d"
      define_method(:install) do
        bin.install "tokensaver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.1/tokensaver_0.2.1_linux_arm64.tar.gz"
      sha256 "a47e16ca1a806c2ebd8cf895143119549271e9398b2c4b0384d94777d1b7d37c"
      define_method(:install) do
        bin.install "tokensaver"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokensaver -version")
  end
end
