# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokensaver < Formula
  desc "Local MCP server that turns web pages, PDFs, Office files and JSON into compact, LLM-ready text"
  homepage "https://github.com/use-tokesaver/tokensaver"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.1.0/tokensaver_0.1.0_darwin_amd64.tar.gz"
      sha256 "1697aa4c6d5d0ea65ef4e2298028550bc8a1316f0f3ecbb72847421f90d6ec80"

      def install
        bin.install "tokensaver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.1.0/tokensaver_0.1.0_darwin_arm64.tar.gz"
      sha256 "367fe447531c3a483103b946956ce23cf590fb5f7ba3f66a32c7dc0ddc51d476"

      def install
        bin.install "tokensaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.1.0/tokensaver_0.1.0_linux_amd64.tar.gz"
      sha256 "056b421d33273842eb2b74fe29baea8b0497ce24d6a238236464c16c1ab0b5fd"
      def install
        bin.install "tokensaver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.1.0/tokensaver_0.1.0_linux_arm64.tar.gz"
      sha256 "8333ee7ae78dcd559ae89d2b7584895f8540ec61c0ffb36f8cabda7c05bf8934"
      def install
        bin.install "tokensaver"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokensaver -version")
  end
end
