# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokensaver < Formula
  desc "Local MCP server that turns web pages, PDFs, Office files and JSON into compact, LLM-ready text"
  homepage "https://github.com/use-tokesaver/tokensaver"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.2/tokensaver_0.2.2_darwin_amd64.tar.gz"
      sha256 "4e540e4c2cbb0e435e12ba7e0d0a378a1a1914a4279f38f82bf7ba94288284ec"

      define_method(:install) do
        bin.install "tokensaver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.2/tokensaver_0.2.2_darwin_arm64.tar.gz"
      sha256 "b3a1f944e782ef1dbb26b098aac8258f7fb4ff6e44277429548aec7fc6bb237d"

      define_method(:install) do
        bin.install "tokensaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.2/tokensaver_0.2.2_linux_amd64.tar.gz"
      sha256 "7b735988402d4648660aa5476c2035dd604338d55574efb7d69f2df8d63c5898"
      define_method(:install) do
        bin.install "tokensaver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/use-tokesaver/tokensaver/releases/download/v0.2.2/tokensaver_0.2.2_linux_arm64.tar.gz"
      sha256 "1f595502698bf8c62be8b17d0377c887ea873b6d69924f4c3e0b3ec0f9d0441f"
      define_method(:install) do
        bin.install "tokensaver"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokensaver -version")
  end
end
